apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-tracker-api
  namespace: price-tracker
  labels:
    app: price-tracker-api
    project: price-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-tracker-api
  template:
    metadata:
      labels:
        app: price-tracker-api
        project: price-tracker
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: price-tracker-api
        image: globoglobitos/price-tracker-api:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "price_tracker_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
      restartPolicy: Always 