apiVersion: v1
kind: Service
metadata:
  name: price-tracker-api-service
  namespace: price-tracker
  labels:
    app: price-tracker-api
    project: price-tracker
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: price-tracker-api 