apiVersion: batch/v1
kind: CronJob
metadata:
  name: ebay-scraper
  namespace: price-tracker
  labels:
    app: price-tracker
    component: scraper
spec:
  schedule: "@hourly"
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: price-tracker
            component: scraper
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: docker-registry-secret
          containers:
            - name: scraper
              image: docker.io/globoglobitos/price-tracker-scraper:latest
              imagePullPolicy: Always
              env:
                # Database connection (use existing postgres-secret)
                - name: DB_HOST
                  value: "postgres-service"
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  value: "price_tracker_db"
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: SEARCH_TERM
                  value: "Selmer Mark VI"
                - name: MAX_PAGES
                  value: "2"
                - name: HEADLESS
                  value: "true"
                - name: BROWSER
                  value: "chromium"
                # Proxy configuration
                - name: HTTP_PROXY
                  valueFrom:
                    secretKeyRef:
                      name: scraper-proxy
                      key: http_proxy
                      optional: true
                - name: HTTPS_PROXY
                  valueFrom:
                    secretKeyRef:
                      name: scraper-proxy
                      key: https_proxy
                      optional: true
                - name: NO_PROXY
                  value: ".svc,.cluster.local,localhost,127.0.0.1"
              resources:
                requests:
                  cpu: "250m"
                  memory: "512Mi"
                limits:
                  cpu: "500m"
                  memory: "1Gi"

