apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-tracker
  labels:
    app: price-tracker
    project: price-tracker
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-tracker
  template:
    metadata:
      labels:
        app: price-tracker
        project: price-tracker
        environment: development
    spec:
      # Use image pull secret for Docker Hub
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: price-tracker
        image: globoglobitos/price-tracker:0.1.0
        imagePullPolicy: Always  # For development, always pull latest
        ports:
        - containerPort: 8000
          name: http
        env:
        # Database connection - using Helm-deployed PostgreSQL service
        - name: DB_HOST
          value: "price-tracker-postgres-postgresql.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "price_tracker_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: price-tracker-postgres-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: price-tracker-postgres-credentials
              key: password
        # Application configuration from ConfigMap
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        - name: SCRAPE_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SCRAPE_INTERVAL
        # Application secrets
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        # WSL2 optimizations
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Security context for WSL2
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false  # Allow for logs and temp files
        # Health checks - uncomment when you have proper health endpoints
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 3
        
