apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-tracker
  template:
    metadata:
      labels:
        app: price-tracker
    spec:
      containers:
      - name: price-tracker
        image: globoglobitos/price-tracker:0.1.0
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "price-tracker-postgres-postgresql.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "price_tracker_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: price-tracker-postgres-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: price-tracker-postgres-credentials
              key: password
        
