apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: price-tracker

# Namespace
namespace: price-tracker

# Resources to include
resources:
  - configmaps.yaml
  - manifests/db-deployment.yaml
  - api-deployment.yaml
  - api-service.yaml
  - cronjob-scraper.yaml

# Common labels applied to all resources
commonLabels:
  project: price-tracker
  environment: development

# Images to replace (not used currently)
# images:
#   - name: globoglobitos/price-tracker
#     newTag: latest

# ConfigMap generator for environment-specific configs
configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - SCRAPE_INTERVAL=3600

# Secret generator (in production, use external secret management)
secretGenerator:
  - name: app-secrets
    literals:
      - API_KEY=your-api-key-here
