apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: price-tracker
type: Opaque
data:
  # Default password is "admin123" (base64 encoded)
  # To change: echo -n "your-password" | base64
  password: YWRtaW4xMjM=
