# Kubernetes Secrets for Price Tracker
# Optimized for WSL2 environment with proper secret management
# Note: In production, use proper secret management tools like Sealed Secrets or External Secrets

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    project: price-tracker
type: Opaque
data:
  # PostgreSQL admin password (base64: price_tracker_admin_password -> cHJpY2VfdHJhY2tlcl9hZG1pbl9wYXNzd29yZA==)
  postgres-password: cHJpY2VfdHJhY2tlcl9hZG1pbl9wYXNzd29yZA==
  # PostgreSQL user password (base64: price_tracker_password -> cHJpY2VfdHJhY2tlcl9wYXNzd29yZA==)
  password: cHJpY2VfdHJhY2tlcl9wYXNzd29yZA==

---
apiVersion: v1
kind: Secret
metadata:
  name: price-tracker-postgres-credentials
  labels:
    app: price-tracker
    project: price-tracker
type: Opaque
data:
  # Database connection credentials for the application
  # username: price_tracker_user (base64: cHJpY2VfdHJhY2tlcl91c2Vy)
  # password: price_tracker_password (base64: cHJpY2VfdHJhY2tlcl9wYXNzd29yZA==)
  username: cHJpY2VfdHJhY2tlcl91c2Vy
  password: cHJpY2VfdHJhY2tlcl9wYXNzd29yZA==

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    app: price-tracker
    project: price-tracker
type: kubernetes.io/dockerconfigjson
data:
  # Docker Hub credentials for pulling images
  # This should be created with: kubectl create secret docker-registry docker-registry-secret
  # --docker-server=docker.io --docker-username=<username> --docker-password=<token>
  # For now, this is a placeholder - use the kubectl command instead
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJnbG9ib2dsb2JpdG9zIiwicGFzc3dvcmQiOiJZT1VSX0RPQ0tFUl9UT0tFTl9IRVJFIiwiYXV0aCI6IloyeHZZbTluYkc5aWFYUnZjenBaVDFWU1gwUlBRMHRGVWw5VVQwdEZUbDlJUlZKRiJ9fX0=

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: price-tracker
    project: price-tracker
type: Opaque
data:
  # Application-specific secrets
  # api-key: your-api-key-here (base64: eW91ci1hcGkta2V5LWhlcmU=)
  api-key: eW91ci1hcGkta2V5LWhlcmU=
  # jwt-secret: your-jwt-secret-here (base64: eW91ci1qd3Qtc2VjcmV0LWhlcmU=)
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWhlcmU=
