apiVersion: v1
kind: Service
metadata:
  name: price-tracker-service
  labels:
    app: price-tracker
    project: price-tracker
    environment: development
spec:
  selector:
    app: price-tracker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000  # Must match containerPort above
  type: NodePort

