apiVersion: batch/v1
kind: Job
metadata:
  name: ebay-workers
  namespace: price-tracker
  labels:
    app: ebay-workers
    project: price-tracker
spec:
  parallelism: 8  # 8 parallel workers
  # No completions - worker should process all messages in queue
  ttlSecondsAfterFinished: 3600  # Clean up after 1 hour
  template:
    metadata:
      labels:
        app: ebay-workers
        project: price-tracker
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: worker
        image: globoglobitos/price-tracker-scraper:latest
        command: ["python", "/app/scraper/worker.py"]
        env:
        # Database connection
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "price_tracker_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        # RabbitMQ connection
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: "admin"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: RABBITMQ_VHOST
          value: "price-tracker"
        # Worker configuration
        - name: HEADLESS
          value: "true"
        - name: BROWSER
          value: "chromium"
        - name: USER_DATA_DIR
          value: "/app/local-stuff-ignore/profiles"
        - name: SNAPSHOT_DIR
          value: "/app/local-stuff-ignore/snapshots"
        - name: DEBUG_SNAPSHOT_DIR
          value: "/app/local-stuff-ignore/debug"
        - name: SCREENSHOT_TIMEOUT_MS
          value: "10000"
        - name: CONTENT_TIMEOUT_MS
          value: "5000"
        # Timeout and retry settings
        - name: WAIT_ON_PAGE_S
          value: "8"
        - name: LISTING_MAX_S
          value: "45"
        - name: BLOCK_RECHECK
          value: "true"
        - name: BLOCK_MAX_RETRIES
          value: "3"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: debug-dir
          mountPath: /app/local-stuff-ignore/debug
        - name: snapshots-dir
          mountPath: /app/local-stuff-ignore/snapshots
        - name: profile-dir
          mountPath: /app/local-stuff-ignorelicating
      volumes:
      - name: debug-dir
        hostPath:
          path: /home/globoglobito/repos/price-tracker/local-stuff-ignore/debug
          type: DirectoryOrCreate
      - name: snapshots-dir
        hostPath:
          path: /home/globoglobito/repos/price-tracker/local-stuff-ignore/snapshots
          type: DirectoryOrCreate
      - name: profile-dir
        hostPath:
          path: /home/globoglobito/repos/price-tracker/local-stuff-ignore
          type: DirectoryOrCreate
